apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nightowl

resources:
  - ../../base

# Production image configuration
images:
  - name: registry.olympusdrive.com/nightowl-monitor
    newTag: latest

# Patches for production
patches:
  # Always pull from registry
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: nightowl-monitor

# Note: Production secrets should be pre-created in the cluster
# kubectl create secret generic nightowl-secret \
#   --from-literal=username=ACTUAL_USERNAME \
#   --from-literal=password=ACTUAL_PASSWORD \
#   --from-literal=tenant=ACTUAL_TENANT \
#   -n nightowl
